### ISSUE TITLE
Landscape Support

### ISSUE THREAD

**Issue by break2k** [peterprokop/SwiftOverlays#10]
Even in landscape the overlay will be dealt as portrait.

**Comment by peterprokop** [comment]
@break2k Steps to reproduce? Are you talking about situation when overlay created in one mode (portrait/landscape) and then controller is switched to other mode?

**Comment by break2k** [comment]
Hey peter,

* added in AppDelegate
* started in Portrait
* switched to Landscape Orientation (UI changed already)
* used: ``` SwiftOverlays.showBlockingWaitOverlayWithText("This is blocking overlay!") ```
* overlay transition shown as in portrait from left (landscape left) or right (landscape right)

**Comment by peterprokop** [comment]
@break2k Please check the [latest commit](https://github.com/peterprokop/SwiftOverlays/commit/38ef8263b84e821b1be1617e341f25085eba7144) and LMK if it helps with your problem.

**Comment by break2k** [comment]
looks great. Spasibo
