### ISSUE TITLE
Consider adding Carthage support.

### ISSUE THREAD

**Issue by Shirk** [peterprokop/SwiftOverlays#15]
Hi,
I know SwiftOverlays ist just one file and an easy drop-in installation at that.
But since you're providing a Cocoapods Podfile why not consider to also support [Carthage](https://github.com/Carthage/Carthage).
Carthage is really getting traction for Swift frameworks and it would be great to have SwiftOverlays on it.

Cheers,

**Comment by peterprokop** [comment]
@Shirk Thank you very much for the suggestion, I will add Carthage support shortly.

**Comment by Shirk** [comment]
:+1:

**Comment by peterprokop** [comment]
Done
