### ISSUE TITLE
showNotificationOnTopOfStatusBar show black bar when hiding

### ISSUE THREAD

**Issue by Fredehagelund92** [peterprokop/SwiftOverlays#17]
When hiding showNotificationOnTopOfStatusBar it is showing a blackbar under the view, and first when the chosen view is hided it will remove the black bar?

**Comment by peterprokop** [comment]
Have you installed SwiftOverlays from CocoaPods? Can you please try version from the github?

**Comment by peterprokop** [comment]
This issue should be solved by now
