### ISSUE TITLE
notification view presenting animation?

### ISSUE THREAD

**Issue by Reedyuk** [peterprokop/SwiftOverlays#18]
When you present a notification view, it doesn't animate in, it just appears, whereas when the notification  view disappears, it moves up and fades out nicely.
Can you change the library so that when the notification appears, it appears at the top of the screen and moves down (like the native notification). Effectively the reverse of the disappearing animation.

Thanks

**Comment by peterprokop** [comment]
Thanks for the suggestion, I'll implement it in the nearest future

On Mon, Apr 25, 2016 at 1:16 PM, Andrew Reed <notifications@github.com>
wrote:

> When you present a notification view, it doesn't animate in, it just
> appears, whereas when the notification view disappears, it moves up and
> fades out nicely.
> Can you change the library so that when the notification appears, it
> appears at the top of the screen and moves down (like the native
> notification). Effectively the reverse of the disappearing animation.
>
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/peterprokop/SwiftOverlays/issues/18>
>



-- 
All the best,
Peter Prokop.

**Comment by peterprokop** [comment]
@Reedyuk Can you please check latest release https://github.com/peterprokop/SwiftOverlays/releases/tag/2.0.1 ?

**Comment by Reedyuk** [comment]
Yes perfect, can you please put this version on cocoa pods.

Thanks

**Comment by peterprokop** [comment]
@Reedyuk Updated pod to 2.0.1, please check

**Comment by Reedyuk** [comment]
Confirmed as working, thanks!
