### ISSUE TITLE
swift-3.0 branch requires a higher minimum target than 8.1

### ISSUE THREAD

**Issue by kpapakipos** [peterprokop/SwiftOverlays#25]
These are the target configurations in my Podfile:
use_frameworks!
platform :ios, '8.1'

This is the line in my Podfile for SwiftOverlays:
pod 'SwiftOverlays', :git => 'https://github.com/peterprokop/SwiftOverlays', :branch => 'swift-3.0'

The Swift 2 version, which I was using until recently, worked with iOS 8.1, and this project's readme only says that it requires "iOS 7.0+ (8.0+ if you use Cocoapods)".
When I run pod install, it gives the following printout:
$ pod install
Analyzing dependencies
Pre-downloading: `SwiftOverlays` from `https://github.com/peterprokop/SwiftOverlays`, branch `swift-3.0`
[!] Unable to satisfy the following requirements:
- `SwiftOverlays (from`https://github.com/peterprokop/SwiftOverlays`, branch `swift-3.0`)`required by`Podfile`
- `SwiftOverlays (from`https://github.com/peterprokop/SwiftOverlays`, branch `swift-3.0`)`required by`Podfile`

Specs satisfying the `SwiftOverlays (from`https://github.com/peterprokop/SwiftOverlays`, branch `swift-3.0`)` dependency were found, but they required a higher minimum deployment target.

Changing my podfile to require iOS 9.1 makes the pod install work, but my project would much rather support 8.1. Is there any fix for this? If not, the readme should probably be updated to reflect it.

**Comment by hoang17** [comment]
Same problem, can we make deployment target to 8.0?

**Comment by peterprokop** [comment]
@kpapakipos hey, sorry for the delay. `swift-3.0` is now merged to master and deployment target set to `8.0`
