### ISSUE TITLE
deployment_target

### ISSUE THREAD

**Issue by PierrickCoulon** [peterprokop/SwiftOverlays#26]
Hi,

In one of your last commit you said:  "change deployment to 8.0" 
But on  SwiftOverlays.podspec  there is ios.deployment_target = '9.0'.

It is normal ? Because I can't install with ios deployment target 8.0.
Error of commit or error of podspec ? 

Thank in advance.

**Comment by peterprokop** [comment]
@PierrickCoulon I'm really sorry, need to update podspec. Will try to do that ASAP.

**Comment by PierrickCoulon** [comment]
@peterprokop  Ok no problem thanks.

**Comment by peterprokop** [comment]
@PierrickCoulon pushed new podspec. Can you please check if everything works as expected?

**Comment by PierrickCoulon** [comment]
Hi @peterprokop, everything is fine thanks ! :D
