### ISSUE TITLE
Have this error in xcode 9 in the SwiftOverlays.swift

### ISSUE THREAD

**Issue by powervette** [peterprokop/SwiftOverlays#39]
Incorrect argument label in call(have 'withAttributes:', expected 'attributes:')

line 477 private class methods, labelForText

**Comment by peterprokop** [comment]
@powervette thanks for reporting, will take a look

**Comment by andrealufino** [comment]
+1 for this, I'm having this problem also

**Comment by maysamsh** [comment]
I have the same problem

**Comment by peterprokop** [comment]
@powervette @andrealufino @maysamsh I'm sorry for the delay, this should be fixed now.

**Comment by maysamsh** [comment]
Now it's a new error:
```
The following build commands failed:
	CompileSwift normal arm64 /Users/maysam/Developer/iOS/GreatTweets/Carthage/Checkouts/SwiftOverlays/SwiftOverlays/SwiftOverlays.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

**Comment by peterprokop** [comment]
@maysamsh can you please try again with `github "peterprokop/SwiftOverlays" ~> 4.0.1` in Cartfile?

**Comment by maysamsh** [comment]
The error is gone, thanks.

**Comment by powervette** [comment]
Is this not updated in Cocoapods yet? Not sure how to update it manually.

**Comment by peterprokop** [comment]
@powervette sorry, just pushed 4.0.1 to pods. Can you please try?
Also: use carthage =)

**Comment by powervette** [comment]
cocoa pods  says 4.0.1 installed, but still getting the same error.

**Comment by peterprokop** [comment]
@powervette I've just tried - works for me without any problems. Have you removed copied `SwiftOverlays.swift`? Can you also please try cleaning everything?

**Comment by powervette** [comment]
i uninstalled it, then reinstalled it, cleaned and still get the error. Not sure what is up, maybe I will look into carthage.

**Comment by DSalehi** [comment]
+1 still getting this error using cocoapods with 4.0.1

**Comment by peterprokop** [comment]
@DSalehi what version of Xcode/cocoapods do you use?

**Comment by DSalehi** [comment]
@peterprokop Xcode 9 with Cocoapods v1.3.1

**Comment by outdoorsole** [comment]
Hello -- did this error happen to be updated for CocoaPods?

**Comment by peterprokop** [comment]
The issue is fixed
