### ISSUE TITLE
Add Xcode 10.0 support ?

### ISSUE THREAD

**Issue by ep372** [peterprokop/SwiftOverlays#50]
Hi @peterprokop 
Like #47 do you plan a quick update for the new Xcode 10.0
Thanks

**Comment by peterprokop** [comment]
Hi @ep372 !
Yes, will update shortly. Most likely today or tomorrow.

**Comment by peterprokop** [comment]
Hi @ep372 !
Please check 5.0.1: https://github.com/peterprokop/SwiftOverlays/releases/tag/5.0.1
