### ISSUE TITLE
Indicator getting placed below table header

### ISSUE THREAD

**Issue by wstudios** [peterprokop/SwiftOverlays#7]
The indicator works great except that it is getting place below the table header and also the cell borders.

**Comment by peterprokop** [comment]
@wstudios can you please provide screenshot/gif for the issue? What kind of controller do you use? UITableViewController?

**Comment by wstudios** [comment]
Thank you very much for your prompt reply. I am using both UITableViewController and table inside of a view. In both cases it occurs but I think i narrowed it down to the use of custom cells. It seems to work fine in tables that have subtitle or basic. I have attached both cases that it occurs in my project.
![loading_1](https://cloud.githubusercontent.com/assets/660143/7912515/298f68a0-0836-11e5-920c-167ae68fd033.jpg)
![loading_2](https://cloud.githubusercontent.com/assets/660143/7912519/2f2c695c-0836-11e5-8269-31a4f2171cf7.jpg)

Hope this helps, thanks.

**Comment by peterprokop** [comment]
@wstudios I suggest using simple UIViewController instead of UITableViewController and adding UITableView as a subview. The problem is that UITableViewController's view is actually a UITableView.

If for some reason you can't use UIViewController, you can do something like:
```SwiftOverlays.showCenteredWaitOverlayWithText(self.view.superview!, text: "Please wait...")
SwiftOverlays.removeAllOverlaysFromView(self.view.superview!)
```
(but in that case overlay will be added to the superview).

**Comment by wstudios** [comment]
Thanks very much for the reply, unfortunately when I add that code the app crashes with the following error:
fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by peterprokop** [comment]
You should obviously do that only if superview is available - for example in **viewDidAppear** method of your controller.
