### ISSUE TITLE
A background to disable any action in the controller

### ISSUE THREAD

**Issue by jose920405** [peterprokop/SwiftOverlays#9]

**Comment by peterprokop** [comment]
@jose920405 Do you want to disable only current controller, or a window entirely (if you use tab bar, for example, results will be different)? Or both?

**Comment by jose920405** [comment]
OK. Makes sense to disable the entire window.

Thanks!.

**Comment by peterprokop** [comment]
@jose920405 Check v0.14 https://github.com/peterprokop/SwiftOverlays/tree/0.14
